spring.application.name=GYM_Management
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/GYM
spring.datasource.username=root
spring.datasource.password=shashank4848
 #JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081

jwt.secret=ThisIsMyVerySecureSecretKeyForGymMembershipApplication123456789
jwt.expiration=86400000

# File Upload
file.upload-dir=uploads/profile

# Maximum File Size
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

razorpay.key.id=rzp_test_TB6ZbqdkGwaXAa

razorpay.key.secret=5yNrCzQsIy7762SQA8G6pEgM

